version: "3"

volumes:
  kms:

services:
  server:
    restart: on-failure
    container_name: paperwork-server
    image: node:lts
    environment:
      DATABASE_URL: postgres://paperwork:password-paperwork@paperwork-db.chu3ouepmzp7.us-east-1.rds.amazonaws.com:5432/postgres
      NODE_ENV: development
      PORT: 8080
    ports:
      - "8080:8080"
    command: "sh -c 'cd /app && npm install && npm run dev'"
    volumes:
      - ./:/app
      - kms:/usr/share/data
      - /usr/src/app/node_modules

  database:
    restart: on-failure
    container_name: database
    image: postgres:latest
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

  serverLocal:
    restart: on-failure
    container_name: paperwork-server-local
    image: node:lts
    environment:
      DATABASE_URL: postgres://user:pass@database:5432/db
      NODE_ENV: development
      PORT: 8080
    ports:
      - "8080:8080"
    command: "sh -c 'cd /app && npm install && npm run dev'"
    volumes:
      - ./:/app
      - kms:/usr/share/data
      - /usr/src/app/node_modules

  test:
      container_name: paperwork-test
      image: node:lts
      depends_on:
        - database
      environment:
        DATABASE_URL: postgres://user:pass@database:5432/db
        NODE_ENV: development
        PORT: 8181
      ports:
        - "8181:8181"
      command: "sh -c 'cd /app && npm install && npm run test:coverage'"
      volumes:
        - ./:/app
        - kms:/usr/share/data
        - /usr/src/app/node_modules