version: "3"

volumes:
  kms:

services:
  server:
    restart: on-failure
    container_name: paperwork-server
    image: node:lts
    environment:
      DATABASE_URL: postgres://paperwork:password-paperwork@paperwork-db.chu3ouepmzp7.us-east-1.rds.amazonaws.com:5432/postgres
      NODE_ENV: development
      PORT: 8080
    ports:
      - "8080:8080"
    command: "sh -c 'cd /app && npm install && npm run dev'"
    volumes:
      - ./:/app
      - kms:/usr/share/data
      - /usr/src/app/node_modules
